
let Recipe = class {
    constructor(name, image, ingredients, ) {
      this.name = name;
      this.locked = false;
      this.ingredients = ingredients; // Needs to be an array of objects containing: ingriedient, amount and maybe brand?
      this.image = image;
      
    }
};

// let Ingredient = class {
//     constructor(name) {
//         this.name
//     }
// }


// let Ingredient = class {
//     constructor(name, brand, ingredients) {
//         this.name = name;
//         this.id = id; // here we could also use an id generator
//         this.ingredients = ingredients; // Needs to be an array of objects containing: ingriedient, amount and maybe brand?
//       }
// }

// ingrident could have the same amount in differnet units of meassuremnet

let img = 'https://www.valdemarsro.dk/wp-content/2022/02/vegetar-tarteletter_svampe.jpg'


const Gyros = new Recipe("Gyros", img, [{ingredient: "Pitabrød", amount: 6, unit: "stk"}, {ingredient: "Kyllingebryst", amount: 200, unit: "gram"}, {ingredient: "Græsk Yogurt", amount: 1, unit: "deciliter"}, {ingredient: "Græsk Yogurt", amount: 1, unit: "deciliter"}, {ingredient: "Citron", amount: 1, unit: "stk"}, {ingredient: "Tomat", amount: 4, unit: "stk"}, {ingredient: "Rødløg", amount: 1, unit: "stk"}, {ingredient: "Koriander", amount: 1, unit: "tsk"}, {ingredient: "Hvidløg", amount: 1, unit: "fed"}, {ingredient: "Røget paprika", amount: 2, unit: "spsk"}, {ingredient: "Tørret Timian", amount: 1, unit: "spsk"}, {ingredient: "Hjertesalat", amount: 1, unit: "stk"}, {ingredient: "Olivenolie", amount: 1, unit: "spsk"}])
const Halloumi_Tacos = new Recipe("Halloumi Tacos", img, [{ingredient: "Halloumi", amount: 200, unit: "gram"}, {ingredient: "Rødløg", amount: 2, unit: "stk"}, {ingredient: "Tomat", amount: 2, unit: "stk"}, {ingredient: "Hjertesalat", amount: 1, unit: "stk"}, {ingredient: "Tortilla pandekager", amount: 6, unit: "stk"}, {ingredient: "Avocado", amount: 1, unit: "stk"}, {ingredient: "Mayonaise", amount: 25, unit: "gram"}, {ingredient: "Citron", amount: 1, unit: "stk"}, {ingredient: "Hvidløg", amount: 1, unit: "fed"}, {ingredient: "Agurk", amount: 1, unit: "stk"}, {ingredient: "Tørret Oregano", amount: 1, unit: "spsk"}])
const Pasta_m_ost_bacon = new Recipe("Paste med ost og bacon", img, [{ingredient: "Frisk Pasta", amount: 2, unit: "pakker"}, {ingredient: "Bacon", amount: 150, unit: "gram"}, {ingredient: "Creme Fraiche", amount: 3, unit: "spsk"}, {ingredient: "Blue Castello", amount: 75, unit: "gram"}, {ingredient: "Broccoli", amount: 1, unit: "stk"}])
const Middelhavs_Havaborre = new Recipe("Middelhavs Havaborre", img, [{ingredient: "Aubergine", amount: 1, unit: "stk"}, {ingredient: "Olivenolie", amount: 1, unit: "spsk"}, {ingredient: "Rødløg", amount: 1, unit: "stk"}, {ingredient: "Hvidløg", amount: 1, unit: "stk"}, {ingredient: "Tomat", amount: 2, unit: "stk"}, {ingredient: "Citron", amount: 1, unit: "stk"}, {ingredient: "Hvidvin", amount: 1, unit: "skvt"}, {ingredient: "Grøntsagsbouillon", amount: 2, unit: "spsk"}, {ingredient: "Hakket Tomat", amount: 2, unit: "spsk"}, {ingredient: "Tørret Oregano", amount: 1, unit: "spsk"}, {ingredient: "Havborre", amount: 300, unit: "gram"}, {ingredient: "Couscous", amount: 250, unit: "gram"}, {ingredient: "Hakkede Oliven", amount: 50, unit: "gram"}])
const Spicy_Oksekød_på_Bulgur = new Recipe("Spicy Oksekød på Bulgur", img,[{ingredient: "Hakket Oksekød", amount: 250, unit: "gram"}, {ingredient: "Gulerød", amount: 2, unit: "stk"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Ærter", amount: 100, unit: "gram"}, {ingredient: "Rødløg", amount: 1, unit: "stk"}, {ingredient: "Rosiner", amount: 50, unit: "gram"}, {ingredient: "Paprika", amount: 1, unit: "tsk"}, {ingredient: "Spidskommen", amount: 2, unit: "tsk"}, {ingredient: "Chiliflager", amount: 1, unit: "tsk"}, {ingredient: "Citronsaft", amount: 1, unit: "spsk"}, {ingredient: "Fuldkornsbulgur", amount: 1.5, unit: "deciliter"}, {ingredient: "Boullionterning", amount: 1, unit: "stk"}])
const Lasagne = new Recipe("Lasagne", img,[{ingredient: "Hakket Oksekød", amount: 250, unit: "gram"}, {ingredient: "Gulerød", amount: 2, unit: "stk"}, {ingredient: "Hvidløg", amount: 3, unit: "fed"}, {ingredient: "Bladselleri", amount: 3, unit: "stilke"}, {ingredient: "Rødløg", amount: 1, unit: "stk"}, {ingredient: "Tomatpure", amount: 35, unit: "gram"}, {ingredient: "Hakkede Tomater", amount: 400, unit: "gram"}, {ingredient: "Oksebouillonterning", amount: 1, unit: "stk"}, {ingredient: "Basilikum", amount: 1, unit: "tsk"}, {ingredient: "Paprika", amount: 1, unit: "tsk"}, {ingredient: "Mælk", amount: 4, unit: "deciliter"}, {ingredient: "Mozerella", amount: 200, unit: "gram"}, {ingredient: "Lasagneplader", amount: 200, unit: "gram"}])
const Fiskefrikadeller_m_ovn_kartofler_og_gulerodssalat = new Recipe("Fiskefrikadeller m ovn-kartofler og gulerodssalat", img, [{ingredient: "Rødløg", amount: 1, unit: "stk"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Torskefars", amount: 150, unit: "gram"}, {ingredient: "Laksefars", amount: 150, unit: "gram"}, {ingredient: "Æg", amount: 1, unit: "stk"}, {ingredient: "Dild", amount: 1, unit: "Håndfuld"}, {ingredient: "Hvedemel", amount: 20, unit: "gram"}, {ingredient: "Smør", amount: 1, unit: "spsk"}, {ingredient: "Gulerod", amount: 3, unit: "stk"}, {ingredient: "Æble", amount: 2, unit: "stk"}, {ingredient: "Honning", amount: 1, unit: "spsk"}, {ingredient: "Rosiner", amount: 100, unit: "gram"}])
const Fajita_Bowl = new Recipe("Fajita Bowl", img, [{ingredient: "Kyllingefond-terninger", amount: 2, unit: "stk"}, {ingredient: "Ris", amount: 200, unit: "gram"}, {ingredient: "Kyllingebryst", amount: 200, unit: "gram"}, {ingredient: "Pepperfrugt", amount: 2, unit: "stk"}, {ingredient: "Løg", amount: 2, unit: "stk"}, {ingredient: "Kidneybønner", amount: 1, unit: "Dåse"}, {ingredient: "Salsa", amount: 200, unit: "gram"}, {ingredient: "Paprika", amount: 1, unit: "tsk"}, {ingredient: "Koriander", amount: 1, unit: "tsk"}, {ingredient: "Spidskommen", amount: 1, unit: "spsk"}, {ingredient: "Hvidløg", amount: 2, unit: "fed"}])
const Chili_sin_carne = new Recipe("Chili sin carne", img,[{ingredient: "Spidskommen", amount: 1, unit: "spsk"}, {ingredient: "Kanel", amount: 1, unit: "tsk"}, {ingredient: "Koriander", amount: 1, unit: "tsk"}, {ingredient: "Chiliflager", amount: 0.5, unit: "tsk"}, {ingredient: "Løg", amount: 1, unit: "stk"}, {ingredient: "Kidneybønner", amount: 1, unit: "Dåse"}, {ingredient: "Salsa", amount: 100, unit: "gram"}, {ingredient: "Paprika", amount: 1, unit: "tsk"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Bladselleri", amount: 2, unit: "stænger"}, {ingredient: "Aubergine", amount: 0.5, unit: "stk"}, {ingredient: "Soltørrede Tomater", amount: 2, unit: "spsk"}, {ingredient: "Hakkede Tomater", amount: 1, unit: "dåse"}, {ingredient: "Grøntsagsbouillon", amount: 1, unit: "deciliter"}, {ingredient: "Mørk chokolade", amount: 30, unit: "gram"}, {ingredient: "Olivenolie", amount: 1, unit: "spsk"}, {ingredient: "Brune ris", amount: 200, unit: "gram"}, {ingredient: "Creme fraiche", amount: 50, unit: "gram"}, {ingredient: "Cheddarost", amount: 100, unit: "gram"}, {ingredient: "Lime", amount: 1, unit: "stk"}])
const Sød_chililaks = new Recipe("Sød chililaks", img, [{ingredient: "Grøntsagsboulion", amount: 1, unit: "stk"}, {ingredient: "Ris", amount: 150, unit: "gram"}, {ingredient: "Gulerod", amount: 1, unit: "stk"}, {ingredient: "Pak Choi", amount: 200, unit: "gram"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Ingefær", amount: 0.5, unit: "stk"}, {ingredient: "Hvidløg", amount: 1, unit: "stk"}, {ingredient: "Forårsløg", amount: 1, unit: "stk"}, {ingredient: "Lime", amount: 1, unit: "stk"}, {ingredient: "Soya", amount: 25, unit: "milliliter"}, {ingredient: "Sød chilisauce", amount: 40, unit: "gram"}, {ingredient: "Laksefilet", amount: 250, unit: "gram"}])
const Boller_i_karry = new Recipe("Boller i karry", img,[{ingredient: "Grøntsagsboulion", amount: 1, unit: "stk"}, {ingredient: "Ris", amount: 150, unit: "gram"}, {ingredient: "Gulerod", amount: 1, unit: "stk"}, {ingredient: "Pak Choi", amount: 200, unit: "gram"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Ingefær", amount: 0.5, unit: "stk"}, {ingredient: "Hvidløg", amount: 1, unit: "stk"}, {ingredient: "Forårsløg", amount: 1, unit: "stk"}, {ingredient: "Lime", amount: 1, unit: "stk"}, {ingredient: "Soya", amount: 25, unit: "milliliter"}, {ingredient: "Sød chilisauce", amount: 40, unit: "gram"}, {ingredient: "Laksefilet", amount: 250, unit: "gram"}])
const Mexi_Bowl = new Recipe("Mexi Bowl", img,[{ingredient: "Grøntsagsboulion", amount: 1, unit: "stk"}, {ingredient: "Ris", amount: 150, unit: "gram"}, {ingredient: "Gulerod", amount: 1, unit: "stk"}, {ingredient: "Pak Choi", amount: 200, unit: "gram"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Ingefær", amount: 0.5, unit: "stk"}, {ingredient: "Hvidløg", amount: 1, unit: "stk"}, {ingredient: "Forårsløg", amount: 1, unit: "stk"}, {ingredient: "Lime", amount: 1, unit: "stk"}, {ingredient: "Soya", amount: 25, unit: "milliliter"}, {ingredient: "Sød chilisauce", amount: 40, unit: "gram"}, {ingredient: "Laksefilet", amount: 250, unit: "gram"}])
const Buddha_Bowl = new Recipe("Buddha Bowl", img, [{ingredient: "Grøntsagsboulion", amount: 1, unit: "stk"}, {ingredient: "Ris", amount: 150, unit: "gram"}, {ingredient: "Gulerod", amount: 1, unit: "stk"}, {ingredient: "Pak Choi", amount: 200, unit: "gram"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Ingefær", amount: 0.5, unit: "stk"}, {ingredient: "Hvidløg", amount: 1, unit: "stk"}, {ingredient: "Forårsløg", amount: 1, unit: "stk"}, {ingredient: "Lime", amount: 1, unit: "stk"}, {ingredient: "Soya", amount: 25, unit: "milliliter"}, {ingredient: "Sød chilisauce", amount: 40, unit: "gram"}, {ingredient: "Laksefilet", amount: 250, unit: "gram"}])
const Wienerschnitzel = new Recipe("Wienerschnitzel", img,[{ingredient: "Grøntsagsboulion", amount: 1, unit: "stk"}, {ingredient: "Ris", amount: 150, unit: "gram"}, {ingredient: "Gulerod", amount: 1, unit: "stk"}, {ingredient: "Pak Choi", amount: 200, unit: "gram"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Ingefær", amount: 0.5, unit: "stk"}, {ingredient: "Hvidløg", amount: 1, unit: "stk"}, {ingredient: "Forårsløg", amount: 1, unit: "stk"}, {ingredient: "Lime", amount: 1, unit: "stk"}, {ingredient: "Soya", amount: 25, unit: "milliliter"}, {ingredient: "Sød chilisauce", amount: 40, unit: "gram"}, {ingredient: "Laksefilet", amount: 250, unit: "gram"}])
const Panang_karry = new Recipe("Panang karry", img,[{ingredient: "Grøntsagsboulion", amount: 1, unit: "stk"}, {ingredient: "Ris", amount: 150, unit: "gram"}, {ingredient: "Gulerod", amount: 1, unit: "stk"}, {ingredient: "Pak Choi", amount: 200, unit: "gram"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Ingefær", amount: 0.5, unit: "stk"}, {ingredient: "Hvidløg", amount: 1, unit: "stk"}, {ingredient: "Forårsløg", amount: 1, unit: "stk"}, {ingredient: "Lime", amount: 1, unit: "stk"}, {ingredient: "Soya", amount: 25, unit: "milliliter"}, {ingredient: "Sød chilisauce", amount: 40, unit: "gram"}, {ingredient: "Laksefilet", amount: 250, unit: "gram"}])
const Tikka_Massala = new Recipe("Tikka Massala",img, [{ingredient: "Grøntsagsboulion", amount: 1, unit: "stk"}, {ingredient: "Ris", amount: 150, unit: "gram"}, {ingredient: "Gulerod", amount: 1, unit: "stk"}, {ingredient: "Pak Choi", amount: 200, unit: "gram"}, {ingredient: "Squash", amount: 0.5, unit: "stk"}, {ingredient: "Ingefær", amount: 0.5, unit: "stk"}, {ingredient: "Hvidløg", amount: 1, unit: "stk"}, {ingredient: "Forårsløg", amount: 1, unit: "stk"}, {ingredient: "Lime", amount: 1, unit: "stk"}, {ingredient: "Soya", amount: 25, unit: "milliliter"}, {ingredient: "Sød chilisauce", amount: 40, unit: "gram"}, {ingredient: "Laksefilet", amount: 250, unit: "gram"}])


let recipeData = [Gyros, Halloumi_Tacos, Pasta_m_ost_bacon, Middelhavs_Havaborre, Spicy_Oksekød_på_Bulgur, Lasagne, Fiskefrikadeller_m_ovn_kartofler_og_gulerodssalat, Fajita_Bowl, Chili_sin_carne, Sød_chililaks, Boller_i_karry, Mexi_Bowl, Buddha_Bowl, Wienerschnitzel, Panang_karry, Tikka_Massala]

export default recipeData;

